# Channel list
---
jhxwzhtv:
  name:
    - 金华新闻综合
  scraper:
    tvmao: JINHUATV1
  refresh: once
  recap: 7
  preview: 2

jhjykjtv:
  name:
    - 金华教育科技
  scraper:
    tvmao: JINHUATV2
  refresh: once
  recap: 7
  preview: 2

jhggpdtv:
  name:
    - 金华公共频道
  scraper:
    tvmao: JINHUATV3
  refresh: once
  recap: 7
  preview: 2

lsxwtv:
  name:
    - 丽水新闻
  scraper:
    tvmao: LSXW
  refresh: once
  recap: 7
  preview: 2

lsggtv:
  name:
    - 丽水公共
  scraper:
    tvmao: LSGG
  refresh: once
  recap: 7
  preview: 2

wzxwtv:
  name:
    - 温州新闻综合
  scraper:
    tvmao: WZTV1
  refresh: once
  recap: 7
  preview: 2

ningbo1tv:
  name:
    - 宁波1
  scraper:
    tvmao: NBTV1
  refresh: once
  recap: 7
  preview: 2

ningbo2tv:
  name:
    - 宁波2
  scraper:
    tvmao: NBTV2
  refresh: once
  recap: 7
  preview: 2

ningbo3tv:
  name:
    - 宁波3
  scraper:
    tvmao: NBTV3
  refresh: once
  recap: 7
  preview: 2

ningbo4tv:
  name:
    - 宁波4
  scraper:
    tvmao: NBTV4
  refresh: once
  recap: 7
  preview: 2

zjhzzhtv:
  name:
    - 湖州综合
  scraper:
    tvmao: HUZHOUTV1
  refresh: once
  recap: 7
  preview: 2

zjhzwhtv:
  name:
    - 湖州文化
  scraper:
    tvmao: HUZHOUTV2
  refresh: once
  recap: 7
  preview: 2

zjhzggtv:
  name:
    - 湖州公共
  scraper:
    tvmao: HUZHOUTV3
  refresh: once
  recap: 7
  preview: 2

zjjxxwtv:
  name:
    - 嘉兴新闻综合
  scraper:
    tvmao: JIAXINTV1
  refresh: once
  recap: 7
  preview: 2

zjjxwhtv:
  name:
    - 嘉兴文化影视
  scraper:
    tvmao: JIAXINTV2
  refresh: once
  recap: 7
  preview: 2

zjjxggtv:
  name:
    - 嘉兴公共频道
  scraper:
    tvmao: JIAXINTV3
  refresh: once
  recap: 7
  preview: 2
